Metrics/LineLength:
  Max: 150

Style/EmptyLinesAroundBlockBody:
  EnforcedStyle: no_empty_lines

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

AllCops:
  TargetRubyVersion: 2.3

Style/Encoding:
  EnforcedStyle: always

Rails:
  Enabled: true

Style/Copyright:
  Enabled: true
  Notice: '^# [A|a]uthor: (.*) <(.*)>$'
  AutocorrectNotice: '# author: Vadim Shaveiko <@vshaveyko>'
