Metrics/LineLength:
  Max: 150

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  SupportedStyles:
    - nested
    - compact

AllCops:
  TargetRubyVersion: 2.3

Style/Copyright:
  Enabled: true
  Notice: '^# [A|a]uthor: (.*) <(.*)>$'
  AutocorrectNotice: '# author: Vadim Shaveiko <@vshaveyko>'
